### ISSUE TITLE
Adobe XD Plugin [EPIC]

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/designengine-xd#88]
Below are all the tasks to complete 1.0 of our XD Plugin for XD submission.

- [ ] Component support for nested / multiple elements (DB / Plugin / NPM) [https://github.com/de-ai/designengine-xd/issues/90](url)

- [x] Calc padding / margin / box model [https://github.com/de-ai/designengine-xd/issues/91](url)

- [x] Separate scenegraph edit logic from UI component [https://github.com/de-ai/designengine-xd/issues/92](url)

- [ ] Final Layer Grouping [https://github.com/de-ai/designengine-xd/issues/94](url)

- [ ] Final Layer Nomenclature [https://github.com/de-ai/designengine-xd/issues/95](url)

- [ ] Final Code Inspect Data Values [https://github.com/de-ai/designengine-xd/issues/96](url)
